import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
  title = 'ngPerformance';

  ELEMENT_DATA = [
    {"weight": 101, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 32, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 32, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 32, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 32, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 32, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 32, "symbol": "W"},
    {"weight": 128, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 101, "symbol": "W"},
    {"weight": 2, "symbol": "H"},
    {"weight": 5.5, "symbol": "H"},
    {"weight": 128, "symbol": "H"},
    {"weight": 64, "symbol": "w"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 1.99, "symbol": "H"},
    {"weight": 2, "symbol": "H"},
    {"weight": 128, "symbol": "H"}
  ];

  returnFullData(symbol:string){
    console.log("function calling");
    if(symbol == 'H')
    {
      return 'Height';
    }else if(symbol == 'W')
    {
      return 'Weight';
    }else{
      return 'Null'
    }
  }

}
